version: '3'
services:
  this_jupyter:
    build: docker/jupyter
    ports:
      - "8888:8888"
    volumes:
      - .:/home/jovyan
    command: start-notebook.sh --NotebookApp.token=""
  this_postgres:
    build: docker/postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
  this_mongo:
    image: mongo
    volumes:
      - mongo_data:/data/db
volumes:
  postgres_data:
  mongo_data:
